In [2]:
#Sampling Tensors
import torch

In [2]:
#random sampling of tensors
torch.manual_seed(1234)

In [3]:
torch.rand(4,4)

tensor([[0.0290, 0.4019, 0.2598, 0.3666],
        [0.0583, 0.7006, 0.0518, 0.4681],
        [0.6738, 0.3315, 0.7837, 0.5631],
        [0.7749, 0.8208, 0.2793, 0.6817]])

In [5]:
#uniform random sampling for tensor
torch.Tensor(4,4).uniform_(0,1)

tensor([[0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294],
        [0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343]])

In [6]:
#Bernoulli distribution
torch.bernoulli(torch.Tensor(4,4).uniform_(0,1))

tensor([[0., 0., 0., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 1.],
        [0., 0., 0., 0.]])

In [7]:
# multinomial distribution picks up without a replacement
torch.Tensor([12,23,34,45,56,67,78,89,90])

tensor([12., 23., 34., 45., 56., 67., 78., 89., 90.])

In [9]:
torch.multinomial(torch.tensor([12. ,23. ,34. ,
                                45. , 56. ,67. ,
                                78. ,89. ,90. ]),
                  3)

tensor([7, 6, 5])

In [10]:
torch.multinomial(torch.tensor([12. ,23. ,34. ,
                                45. , 56. ,67. ,
                                78. ,89. ,90. ]),
                  3, replacement=True)

tensor([1, 6, 5])

In [13]:
#creating a set of random weights generated from a normal distribution.
torch.normal(mean=torch.arange(1.,11.),
             std=torch.arange(1,0,-0.1))

tensor([ 2.2826,  2.1101,  3.3422,  4.2391,  5.6165,  6.5432,  6.4072,  7.8412,
         8.9324, 10.0984])

In [3]:
torch.normal(mean=3.14,std=torch.arange(0.2,0.67789))

tensor([3.1352])

In [4]:
#Variable Tensors (RANDOM VARIABLE IN PyTorch)
#imoplementation of Autograd module
from torch.autograd import Variable

In [5]:
Variable(torch.ones(2,2),requires_grad=True)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [6]:
a,b=12,23
x1=Variable(torch.randn(a,b),requires_grad=True)
x2=Variable(torch.randn(a,b),requires_grad=True)
x3=Variable(torch.randn(a,b),requires_grad=True)

In [7]:
c=x2*x1
d=a+x2
e=torch.sum(d)
e.backward()
print(e)

tensor(3330.1995, grad_fn=<SumBackward0>)


In [8]:
#introductory statistic in tensors (mean, median, mode). NOTE Torch functions have GPU acceleration
#mean for 1D tensor
torch.mean(torch.tensor([12.,23.,34.,45.,56.,67.,78.,89.,90.]))

tensor(54.8889)

In [10]:
#mean across rows and columns of multi-dimension tensors
d=torch.randn(5,5)
d

tensor([[ 1.4786,  0.2932, -0.6198, -0.6926, -0.5230],
        [ 0.0277,  0.0033, -1.2944, -1.2800,  0.5592],
        [-0.7738, -0.0886,  0.1204,  0.7204,  0.3337],
        [-1.1497,  0.7606, -1.9451, -1.8636, -0.2904],
        [ 0.5290, -0.4065,  0.1078, -0.4989, -0.4873]])

In [11]:
torch.mean(d,dim=0)#mean along row

tensor([ 0.0224,  0.1124, -0.7262, -0.7230, -0.0816])

In [12]:
torch.mean(d,dim=1)#mean along col

tensor([-0.0127, -0.3968,  0.0624, -0.8976, -0.1512])

In [13]:
#median
torch.median(d,dim=0)#mean along row
torch.median(d,dim=1)#mean along col

torch.return_types.median(
values=tensor([-0.5230,  0.0033,  0.1204, -1.1497, -0.4065]),
indices=tensor([4, 1, 2, 0, 1]))

In [14]:
#mode
torch.mode(d,dim=0)#mean along row
torch.mode(d,dim=1)#mean along col

torch.return_types.mode(
values=tensor([-0.6926, -1.2944, -0.7738, -1.9451, -0.4989]),
indices=tensor([3, 2, 0, 2, 3]))

In [15]:
#standard deviations
torch.std(d)

tensor(0.8298)

In [16]:
torch.std(d,dim=0)#std along row

tensor([1.0470, 0.4400, 0.8989, 0.9677, 0.4965])

In [17]:
torch.std(d,dim=1)#std along col

tensor([0.9231, 0.8426, 0.5550, 1.1415, 0.4552])

In [18]:
#variance
torch.var(d)

tensor(0.6885)

In [19]:
torch.var(d,dim=0)#std along row

tensor([1.0962, 0.1936, 0.8080, 0.9364, 0.2465])

In [20]:
torch.var(d,dim=1)#std along col

tensor([0.8522, 0.7100, 0.3080, 1.3030, 0.2072])

In [21]:
#computation of gradients of sampled tensors
#consider a sample datase0074, where two variables (x and y) are present

#forward function computes the matrix multiplication of the weight tensor with the input tensor
def forward(x):
  return x*w

In [22]:
import torch
from torch.autograd import Variable

x_data=[11.0,22.0,33.0]
y_data=[54.0,89.09,67.89]

w=Variable(torch.Tensor([1,0]),requires_grad=True)

#prior of training
print("predict (before training)",4,forward(4).data[0])

predict (before training) 4 tensor(4.)


In [28]:
def forward(x):
  return x*w

In [29]:
#introduce loss function
def loss(x,y):
  y_pred=forward(x)
  return (y_pred-y)*(y_pred-y)

In [40]:
#executing training loop
for epoch in range(10):
  for x_val, y_val in zip(x_data,y_data):
    l=loss(x_val,y_val)
    l.backward()
    print("\tgrad: ", x_val, y_val, w.grad.data[0])
    w.data = w.data-0.01*w.grad.data

    #manually setting gradients to 0
    w.grad.data.zero_()
    print("progress:" , epoch, l.data[0])

RuntimeError: grad can be implicitly created only for scalar outputs

In [5]:
from torch import FloatTensor
from torch.autograd import Variable

In [6]:
a=Variable(FloatTensor([5]))

weights= [Variable(FloatTensor([i]),requires_grad=True) for i in (12,91,89,56)]
w1,w2, w3, w4=weights
b=w1*a
c=w2*a
d=w3*b+w4*c
loss=(10-d)
loss.backward()

for index, weights in enumerate(weights,start=1):
  gradient,*__=weights.grad.data
  print(f"gradient of w{index} with respect to loss: {gradient}")

gradient of w1 with respect to loss: -445.0
gradient of w2 with respect to loss: -280.0
gradient of w3 with respect to loss: -60.0
gradient of w4 with respect to loss: -455.0


In [7]:
#Tensor Operations (grad, volatile, gradient)
#Perform matrix multiplication by mm modeule
x=Variable(torch.Tensor(4,4).uniform_(-4,5))
y=Variable(torch.Tensor(4,4).uniform_(-3,2))

In [8]:
x

tensor([[ 2.9111, -1.1113,  2.0239,  1.3368],
        [-2.3053,  1.3786, -0.7065,  4.6133],
        [ 0.2035,  2.8672,  2.1076,  4.8294],
        [-0.7025,  0.0271, -2.7841, -2.5639]])

In [46]:
y

tensor([[-1.9156, -1.8726,  1.0226, -2.3292],
        [-2.0001,  0.1279,  0.5313, -1.6413],
        [-0.4996, -2.3758,  1.2876, -0.6267],
        [-2.7291, -2.9486, -2.2718, -2.7632]])

In [9]:
xmultiplyy=torch.mm(x,y)

In [10]:
z=xmultiplyy

In [49]:
z

tensor([[-21.0577, -18.9734,  -2.8621, -21.1509],
        [ 14.8348,   3.7486,   3.8594,  14.2648],
        [ -7.0854, -11.6179,   4.0567,  -6.5713],
        [  7.0754,  -7.5367,   2.7598,   5.7408]])

In [11]:
z.size()

torch.Size([4, 4])

In [12]:
#properties of the variable
z=Variable(torch.Tensor(4,4).uniform_(-5,5))
print(z)

tensor([[ 3.9654,  2.8418,  4.5645,  0.5791],
        [-3.4296, -4.2381, -3.8777,  1.4841],
        [-1.0304,  1.2935, -2.4219,  0.0192],
        [-2.6667, -3.5739,  2.0413, -2.0858]])


In [13]:
print('Required Gradient: %s ' % (z.requires_grad))
print('Volatile: %s ' % (z.volatile))
print('Grad: %s ' % (z.grad))
print(z.data)

Required Gradient: False 
Volatile: False 
Grad: None 
tensor([[ 3.9654,  2.8418,  4.5645,  0.5791],
        [-3.4296, -4.2381, -3.8777,  1.4841],
        [-1.0304,  1.2935, -2.4219,  0.0192],
        [-2.6667, -3.5739,  2.0413, -2.0858]])


<ipython-input-13-69d0e6fb4537>:2: UserWarning: volatile was removed (Variable.volatile is always False)
  print('Volatile: %s ' % (z.volatile))


In [15]:
#tensor operations (matrix-vector computation, and matrix-matrix and vector-vector calculation)
some_mat1=torch.FloatTensor(4,4).uniform_(0,1)
some_mat1

tensor([[0.7848, 0.1165, 0.8236, 0.9971],
        [0.9884, 0.4494, 0.7886, 0.6796],
        [0.4086, 0.4149, 0.3651, 0.2848],
        [0.7076, 0.7932, 0.2800, 0.8026]])

In [16]:
some_mat2=torch.FloatTensor(4,4).uniform_(0,1)
some_mat2

tensor([[0.1174, 0.0982, 0.2957, 0.8359],
        [0.3346, 0.4318, 0.2329, 0.4929],
        [0.6346, 0.8150, 0.1193, 0.6444],
        [0.7579, 0.3256, 0.5988, 0.8430]])

In [18]:
some_vec1=torch.FloatTensor(4).uniform_(0,1)
some_vec1

tensor([0.8065, 0.3862, 0.0899, 0.5788])

In [19]:
some_mat2+some_mat1

tensor([[0.9022, 0.2147, 1.1193, 1.8329],
        [1.3230, 0.8811, 1.0215, 1.1725],
        [1.0432, 1.2300, 0.4844, 0.9292],
        [1.4655, 1.1188, 0.8788, 1.6456]])

In [20]:
some_mat2+some_mat1+.0998123

tensor([[1.0020, 0.3145, 1.2191, 1.9327],
        [1.4229, 0.9809, 1.1213, 1.2723],
        [1.1431, 1.3298, 0.5842, 1.0290],
        [1.5653, 1.2186, 0.9786, 1.7454]])

In [21]:
some_mat2+some_mat1-.0998123

tensor([[0.8024, 0.1149, 1.0195, 1.7331],
        [1.2232, 0.7813, 0.9217, 1.0727],
        [0.9434, 1.1301, 0.3845, 0.8294],
        [1.3657, 1.0190, 0.7790, 1.5458]])

In [22]:
#matrix and vector addition
some_mat1+some_mat2+some_vec1

tensor([[1.7087, 0.6009, 1.2092, 2.4117],
        [2.1295, 1.2673, 1.1114, 1.7513],
        [1.8497, 1.6161, 0.5742, 1.5080],
        [2.2720, 1.5049, 0.9687, 2.2243]])

In [23]:
some_mat3=torch.FloatTensor(5,4)

In [24]:
some_mat3+some_mat1#obviously not possible due to different sizes of tensors

RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 0

In [25]:
#Distributions on tensors for weight normalization, weight initialization, and computation of gradients in neural network– based operations using PyTorch
#targetting Bernoulli distribution
from torch.distributions.bernoulli import Bernoulli


In [28]:
dist=Bernoulli(torch.tensor([0.3,0.6,0.9]))
dist.sample()

tensor([0., 1., 1.])

In [33]:
#Beta distribution
from torch.distributions.beta import Beta
dist=Beta(torch.tensor([0.9]),torch.tensor([0.9]))
dist.sample()

tensor([0.0913])

In [35]:
#Binomial distribution
from torch.distributions.binomial import Binomial
dist=Binomial(100,torch.tensor([0.9]))
dist.sample()


tensor([90.])

In [40]:
#a generalized Bernoulli distribution called as categorical
from torch.distributions.categorical import Categorical
dist=Categorical(torch.tensor([0.7,0.7,0.7]))
dist.sample()

tensor(0)

In [44]:
#Laplacian distribution
from torch.distributions.laplace import Laplace
dist=Laplace(torch.tensor([7.0]),torch.tensor([0.99]))
dist.sample()

tensor([5.7971])

In [46]:
# normal distribution
from torch.distributions.normal import Normal
dist=Normal(torch.tensor([7.0]),torch.tensor([0.99]))
dist.sample()

tensor([6.4637])